name:                raybow
version:             0.1.0.0
github:              "jcberentsen/raybow"
license:             BSD3
author:              "Jarl Christian Berentsen"
maintainer:          "jc.berentsen@gmail.com"
copyright:           "2018 Jarl Christian Berentsen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jcberentsen/raybow#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  raybow:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wredundant-constraints
    dependencies:
    - raybow
    - ad
    - gloss
    - bytestring

tests:
  raybow-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - raybow
    - ad
    - tasty
    - tasty-discover
    - tasty-hunit
